### ISSUE TITLE
[Feature request] Generalize proxy to allow connections to white-listed URLs

### ISSUE THREAD

**Issue by rbrecheisen** [vantage6/vantage6#162]
Based on our discussion on Discord. So, to reiterate we'd like to allow the algorithm container to connect to XNAT directly instead of having to go through an ETL that pulls the data and stores it inside the Docker volume.

Cheers, Ralph

**Comment by frankcorneliusmartin** [comment]
![image](https://user-images.githubusercontent.com/15981243/205856435-fa13b39a-95fe-4af9-8445-d2c3c1d0accc.png)

* Recommend limiting forwarding to local adresses (1)
* Any proxy container can be used. We investigate the use of _squid_(5), _nginx_(4) and _proxysql_(3).
* The use of proxys can be limited by the collaboration (_master_ in the image)
   * No proxy allowed
   * Local proxy (only forwarding to local adresses) 
   * Any proxy (no limits to the proxy container)

- [ ] Spin up forward proxy container
  - [ ] Attach it to the _node internal_ network 
  - [ ] Attach it to the external network
  - [ ] Set hostname of the proxy containe rin the _internal network_ (e.g. `tunnel`)
- [ ] foward tcp traffic 
  - [ ] Except the traffic that goes into the VPN `10.76.x.x` or what is configured, 
  - [ ] `http_proxy`, `https_proxy` environment variables (6) is not sufficient, see (2)  

(1) https://en.wikipedia.org/wiki/Private_network
(2) https://stackoverflow.com/questions/70971310/how-to-make-docker-container-connect-everything-through-proxy
(3) https://proxysql.com 
(4) https://www.nginx.com/
(5) http://www.squid-cache.org/
(6) https://docs.docker.com/network/proxy/

**Comment by frankcorneliusmartin** [comment]
Connecting to services from the algorithm to services within the docker host network is not trivial. One solution would be (in the case of azure) to assign vnet addresses to the container: https://adamraffe.com/azure/docker/2017/09/18/connecting-containers-to-azure-virtual-networks/

![image](https://user-images.githubusercontent.com/15981243/207314330-7692e0f2-12b1-458f-b199-0b485178ec6c.png)

**Comment by frankcorneliusmartin** [comment]
Another solution would be to add SSH tunnels as an option. This would allow to create a tunnel between `vantage6-[NODE]-user-net` and the docker host (or another remote machine if the default bridge has an internet connection).

The configuration should have these additional fields:

```yaml
  # path or endpoint to the local data source. The client can request a
  # certain database to be used if it is specified here. They are
  # specified as label:local_path pairs.
  databases:
    default: D:\data\datafile.csv
    postgres: postgresql://a:b@<tunnel_name>:5432/<database_name>
  
  # create tunnels to reach external data-sources
  tunnels:
    - hostname: this-is-a-tunnel
      destination:
        ip: 0.0.0.0
        port: 5432
      source: 
        ip: host.docker.internal
        port: 5432
      identity: 
        username: ssh-username
        key: /path/to/private_key.pem
        password: somepassword
```

**Comment by frankcorneliusmartin** [comment]
The SSH Tunnel solution is implemented and waiting to be reviewed and merged. Expect that we can ship this feature in `3.7`.

**Comment by frankcorneliusmartin** [comment]
Enable it by adding an extra block in the configuration file: 

```yaml
# Create SSH Tunnel to connect algorithms to external data-sources. The
     # `hostname` and `tunnel:bind:port` can be used by the algorithm
     # container to connect to the external data-source. This is the address
     # you need to use in the `databases` section of the configuration file!
     ssh-tunnels:

     # Hostname to be used within the internal network. I.e. this is the
     # hostname that the algorithm uses to connect to the data source. Make
     # sure this is unique and the same as what you specified in the
     # `databases` section of the configuration file.
     - hostname: my-data-source

         # SSH configuration of the remote machine
         ssh:

         # Hostname or ip of the remote machine, in case it is the docker
         # host you can use `host.docker.internal` for Windows and MacOS.
         # In the case of Linux you can use `172.17.0.1` (the ip of the
         # docker bridge on the host)
         host: host.docker.internal
         port: 22

         # fingerprint of the remote machine. This is used to verify the
         # authenticity of the remote machine.
         fingerprint: "ssh-rsa ..."

         # Username and private key to use for authentication on the remote
         # machine
         identity:
             username: username
             key: /path/to/private_key.pem

         # Once the SSH connection is established, a tunnel is created to
         # forward traffic from the local machine to the remote machine.
         tunnel:

         # The port and ip on the tunnel container. The ip is always
         # 0.0.0.0 as we want the algorithm container to be able to connect.
         bind:
             ip: 0.0.0.0
             port: 8000

         # The port and ip on the remote machine. If the data source runs on
         # this machine, the ip most likely is 127.0.0.1.
         dest:
             ip: 127.0.0.1
             port: 8000
```

**Comment by frankcorneliusmartin** [comment]
The whitelist (squid) solution is implemented and waiting to be reviewed and merged. Expect that we can ship this feature in 3.9.

Enable it by adding an additional block to the node config:
```yaml
  whitelist:
        domains:
            - .google.com
            - github.com
            - host.docker.internal # docker host ip (windows/mac)
        ips:
            - 172.17.0.1 # docker bridge ip (linux)
            - 8.8.8.8
        ports:
            - 443
```
