### ISSUE TITLE
Settalble VPN_CLIENT_IMAGE and NETWORK_CONFIG_IMAGE

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#163]
These are now fixed from the globals. It would be better if we can overwrite these with custom images, like we do for the node image itself. 

I suggest to change the `image` key in the node-configuration file to:
```yaml
images: 
     node: harbor2.vantage6.ai/infrastucture/node:tag
     vpn_client: harbor2.vantage6.ai/infrastucture/vpn_client:tag
     network_config: harbor2.vantage6.ai/infrastucture/network_config:tag
```

Then we can use them here: 
https://github.com/IKNL/vantage6-node/blob/51b2a4288621fbabdbd3e55dedbf7de312958305/vantage6/node/docker/vpn_manager.py#L129

https://github.com/IKNL/vantage6-node/blob/51b2a4288621fbabdbd3e55dedbf7de312958305/vantage6/node/docker/vpn_manager.py#L329

https://github.com/IKNL/vantage6-node/blob/51b2a4288621fbabdbd3e55dedbf7de312958305/vantage6/node/docker/vpn_manager.py#L413

https://github.com/IKNL/vantage6-node/blob/51b2a4288621fbabdbd3e55dedbf7de312958305/vantage6/node/docker/vpn_manager.py#L63
