### ISSUE TITLE
[Feature Request] [k8s] Replace kube config file mount with k8s Service Account

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#1676]
**Problem description**
The node administrator should be able to mount a kube config file in its favorite location. Currently this needs to be in the home directory. I think this should be a secret?

This is the code that should change in the `container_manager.py`:

```python
home_dir = os.path.expanduser("~")
kube_config_file_path = os.path.join(home_dir, ".kube", "config")
```

And whilst you are there the `if`-`else` section bellow this piece of code should be cleaned. And make a clean exit when the config file has not been found. Make sure that 

```python
raise ValueError(
  "K8S configuration could not be found. Node must be running within a "
  "POD or a host"
)
```

is catched.

**Comment by frankcorneliusmartin** [comment]
A better alternative would be to create a specific ServiceAccount in the namespace of the node. This service account can then be used by the node to access the Kubernetes API. 


```yaml
# Create a Service Account: First, create a service account that your 
# deployment will use to access the Kubernetes API.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: default
```

```yaml
# Bind the Service Account to a Role: Create a role with the necessary 
# permissions and bind it to the service account.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: my-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
```
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: my-service-account
  namespace: default
roleRef:
  kind: Role
  name: my-role
  apiGroup: rbac.authorization.k8s.io
```
Then update the node deployment to use this config file:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: my-service-account
      containers:
      - name: my-container
        image: my-image
        ports:
        - containerPort: 80
```

Note that this is AI generated and not specific to our use case.
