### ISSUE TITLE
[Feature Request] [k8s] Store database connection details in environment variables

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#1892]
See parent issue for motivation.

Use a config map to define environment variables, for example database `"A"`:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  ...
data:
  DATABASE_LABELS: "A, B, C"
  DATABASE_A_URI: ""
  DATABASE_A_TYPE: ""
  DATABASE_A_[*]: "any_other_params"
  ...
```

Then we need to store passwords and such in Kubernetes secrets.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  DATABASE_A_USERNAME: bXktYXBw
  DATABASE_A_PASSWORD: Mzk1MjgkdmRnN0pi
```

- [x] Update the `@source_database.py` to be able to consume both `DATABASE_URI`, `DATABASE_USERNAME` and `DATABASE_PASSWORD` and orter `DB_PARAM_*`s (if present).
- [x] Update the `run()` in `container_manager.py` to create secrets for the *username* and *password* for the database.
- [x] Update the `self._set_database(self.ctx.config["databases"])` in `container_manager.py` to consume environment variables for the databases instead of the config files.
- [x] Update the charts 
	- [x] Remove `databases` section from the configuration file Leave the `fileBased` section (as we need to create file mounts for these)
	- [ ] ~~Add `configMap` for the db connection details~~
	- [x] Add `secrets` for the db connection details 

Note that the `secret` and `configMap` is optional as some sources don't require credentials (typically only file-based sources, but also DB connections can disable authentication). This allows other (parent charts) to specify these themselves.
