### ISSUE TITLE
[Feature Request] Support external databases in v5

### ISSUE THREAD

**Issue by CunliangGeng** [vantage6/vantage6#1919]
**Problem description**

Postgres and RabbitMQ in vantage6 are currently deployed in a "manual" way: we define the k8s resources (`Deployment`, `Service`, `PersistentVolumeClaim`, etc) for them using helm charts. This approach is ok for dev or prototyping, but not for production, since it lacks the [full lifecycle management capabilities](https://sdk.operatorframework.io/docs/overview/operator-capabilities/) (e.g. Fault-tolerant, always-on, and self-recovering).

For production, it's better to use [operators](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/). Operators are k8s [controllers](https://kubernetes.io/docs/concepts/architecture/controller/) for [Custom Resources](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/), it's like putting human operational knowledge into code, so that the system can manage itself.

Using an operator is like using a k8s resource, e.g.:
```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster                                 # The PostgresCluster here is a Custom Resource
metadata:
  name: my-postgres
...
```
The operator will automatically:
- Deploys Pods
- Sets up replication
- Handles storage, TLS, backups
- Watches for failures and recovers
- ...

**Desired solution**

Postgres operators
- https://operatorhub.io/operator/postgres-operator
- https://operatorhub.io/operator/postgresql

RabbitMQ operators
- https://operatorhub.io/operator/rabbitmq-cluster-operator

**TODO**
- [ ] explore which operators meet v6 requirements
