### ISSUE TITLE
[Bug] start-dev fails to listen to server and store ports on WSL

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6#1935]
**Describe the bug**
My output on branch `release/5.0` currently ends with:

```
start_dev: forward ports: unable to listen on any of the requested ports: [{7601 7601} {7601 7601}]
fatal exit status 1
```

I can resolve the issue by uncommenting one of the two exposed ports in devspace.yaml:

```
  vantage6-server-init:
    imageSelector: ${SERVER_IMAGE}
    ports:
      - port: 7601:7601
        bindAddress: localhost
      # - port: 7601:7601
      #   bindAddress: ${PORTS_BIND_ADDRESS}
```

And same for 7602. Can we come up with a solution?

**To Reproduce**
Use WSL?

**Expected behavior**
No errors
