### ISSUE TITLE
[Feature Request] VPN_CLIENT_IMAGE not settable in the configuration file

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#294]
**Problem description**
The image used for the VPN client can not be set in the node configuration file (while the alpine image can be set)

**Desired solution**
add `vpn_client_image` option to the configuration file.

**Comment by frankcorneliusmartin** [comment]
Needs to be documented: 

```yaml
images:
    node: harbor2.vantage6.ai/infrastructure/node:petronas
    alpine: alpine
    vpn_client: client
    network_config: network
```
also the `image` option has become depreciated as it has been replaced.
