### ISSUE TITLE
[Feature Request] Control individual log levels

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#641]
**Problem description**
We can only set the global log level for all loggers and some loggers are manually muted on startup. A much better solution would be to be able to set individual log levels.

**Desired solution**
Add a configuration block to adjust the individual log-levels for the node:

```yaml

# additional debug settings
debug:
  socketio: true
  proxy_server: true

logging:
   ...
  loggers:
    - name: urllib3
      level: warning
    - name: requests
      level: warning
    - name: engineio.client
      level: debug
    - name: docker.utils.config
      level: critical
    - name: docker.auth
      level: info
    - ...
```

And for the server:
```yaml

# additional debug settings
debug:
  socketio: true
  flask: true

logging:
  loggers:
    - name: urllib3
       level: warning
    - name: socketIO-client
       level: warning
    - name: engineio.server
      level: warning
    - name: socketio.server
      level: warning
    - name: sqlalchemy.engine
      level: warning
    - name: requests_oauthlib.oauth2_session
      level: warning
    - ...
```
