### ISSUE TITLE
The way fixtures are loaded is untransparent

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#71]
The function `fixtures.load()` infers which nodes to create based on participations in a collaboration. This also means that API-keys are generated on the fly and cannot be set in advance.

I suggest moving to a fixture system that keeps a close relation to the database:

```yaml
Organization:
  - id: ...
    name: ...

User:
  - id: ...
    organization_id: ...
    username: ...
    password: ...
```

Loading fixtures can then be as easy as:

```python
def load_fixtures(fixtures):
    log.warn("Loading fixtures")

    session = Session()

    for clsname, values in fixtures.items():
        log.debug(f"  - Processing class {clsname}")
        cls = eval(clsname)

        for entry in values:
            instance = cls(**entry)
            session.add(instance)

    session.commit()
```
