### ISSUE TITLE
[Feature Request] Report demo user/password in the logs when using `vdev create-demo-network` 

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#830]
**Problem description**
Now it is unclear to me what the credentials are. It would be good if these would be printed in the end, when the setup is done.

I think per default this would be:

```yaml
users:
    - username: org_1-admin
      firstname: admin
      lastname: robot
      password: password
```
