### ISSUE TITLE
[Bug] Logfile only contains `INFO` (or higher?) logs

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#993]
**Describe the bug**
It seems that I only get `INFO` logging in the logfile even when specified that the log level should be DEBUG in the config file.

```yaml
logging:
  backup_count: 5
  datefmt: '%Y-%m-%d %H:%M:%S'
  file: testing420_node_3.log
  format: '%(asctime)s - %(name)-14s - %(levelname)-8s - %(message)s'
  level: DEBUG
  max_size: 1024
  use_console: true
```

I do see the debug logs when I `attach` the node.

**To Reproduce**
1. start node with debug logging
2. observe that only info or higher is stored in the logfile

**Expected behavior**
I expect the same logging to be present in the logfile as in the attached form.

**Details**
 - Version 4.2.1
