### ISSUE TITLE
[Feature Request] Mute excessive logging in `vdev` nodes. 

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#997]
**Problem description**
The config file does not mute some loggers that are usually not involved with bugs, we should mute them as we do in the default creation process:

```yaml
logging:
  loggers:
      - name: urllib
        level: warning
      - name: requests
        level: warning
      - name: engineio.client
        level: warning
      - name: docker.utils.config
        level: warning
      - name: docker.auth
        level: warning
```
